### ISSUE TITLE
Add Button+ brand to Home Assistant

### ISSUE THREAD

**Issue by koenhendriks** [koenhendriks/ha-button-plus#16]
The images / logo of button+ should be added to https://github.com/home-assistant/brands to ensure the integration UI looks correct without missing images.

**Comment by koenhendriks** [comment]
This also breaks the current CI for HACS validation / linting

![image](https://github.com/koenhendriks/ha-button-plus/assets/4124579/dcce936f-b1ae-4dd4-bd4f-d569dea7b2aa)

**Comment by wimjanse** [comment]
I spend a few minutes on Photoshop, created the 2 icon files and 2 logo files (just made look-a-likes from the Button+ website), all according the specifications for those files.  I have no clue how to get these into the home-assistant brand directory (I'm not that familiar with git commands).
I have included the four files here, with the proper naming. Hope that the files are good enough (for the moment) and that someone can upload those to the brand-directory.

![icon](https://github.com/koenhendriks/ha-button-plus/assets/20152820/9374f731-efb1-4cc1-90cd-4027dec3839e)
![icon@2](https://github.com/koenhendriks/ha-button-plus/assets/20152820/dd5aea24-6fcd-4a31-88ff-9072555c2213)
![logo](https://github.com/koenhendriks/ha-button-plus/assets/20152820/d6a102c7-d24d-4c58-9002-fde9cdfbb13b)
![logo@2](https://github.com/koenhendriks/ha-button-plus/assets/20152820/4a54d765-0b35-444a-805b-7e2004a8c1c0)

**Comment by koenhendriks** [comment]
Thanks @wimjanse, I'll see if I can create an MR for you in the brands repo.

**Comment by wimjanse** [comment]
Koen, I made a mistake with the filenames, I uploaded file with name logo@2.png, should be logo@2x.png, same for icon@2.png,  should be icon@2x.png.

Don't know whether you can change this is in the PR, otherwise here are the (four) files again with proper naming.

Sorry for this.

![icon](https://github.com/koenhendriks/ha-button-plus/assets/20152820/9be22fca-b39f-42e7-9b0d-d8f8bae77ecc)
![icon@2x](https://github.com/koenhendriks/ha-button-plus/assets/20152820/02aaaabc-ee74-4273-bc7b-1421d789f585)
![logo](https://github.com/koenhendriks/ha-button-plus/assets/20152820/83ab781a-66a4-4d6c-a2ef-d02be3c97064)
![logo@2x](https://github.com/koenhendriks/ha-button-plus/assets/20152820/70336fb9-ecf0-409b-9516-9ad75a420f86)

**Comment by koenhendriks** [comment]
Closing as https://github.com/home-assistant/brands/pull/5397 has been merged.
