### ISSUE TITLE
Two B+'s, cannot assign B+ to different areas

### ISSUE THREAD

**Issue by wimjanse** [koenhendriks/ha-button-plus#36]
**Describe the bug**
I added first B+ with ID 45_a450 to HA, area: "Studeerkamer". Then added second B+ with ID 45_a5d0, during addition I see the Display and 3 BARS, already with area "Studeerkamer". When I make a change in area ("Huiskamer") during the addition of the second B+, also the first B+ changes to "Huiskamer"

**To Reproduce**
- Add device B+ nr.1 to Integration, give IP address of B+ no. 1 and thereafter enter area for Display, Bar 1/2/3.
- Add device B+ nr.2 to Integration, give IP address of B+ no. 2, areas for Display and Bar 1/2/3 now show area from no.1
- During this addition, change are for no.2
- Also area for no.1 is changed to same as given above for no.2 

**Expected behavior**
Different areas for the two B+'s

**Comment by nvdweem** [comment]
I think I have a similar issue but it seems to be in reverse. I'll post my issue here, feel free to tell me to put in a new ticket.

I can set labels for the (3 in my case) devices, but the button presses are grouped together. Also, even though the Integration page correctly shows the separate devices, choosing 1 device shows all same-bars combined in 1 device.
The devices have their names changed, their id's have not changed.
![image](https://github.com/koenhendriks/ha-button-plus/assets/830783/9a39463c-034b-44f3-96eb-58626cd0bfd7)

Here you see the 3 devices grouped together. The event viewer shows that all 3 devices were pressed, but that was only 1 device. This also happens when a different device (or bar) is pressed.
![image](https://github.com/koenhendriks/ha-button-plus/assets/830783/7d3f71ee-9148-407c-84ff-8950b80d4694)

The devices post to their correct topics in MQTT (checked all 3 buttons, their topics include their id), MQTT explorer shows a single message for the 3 presses in the screenshot.

**Comment by koenhendriks** [comment]
This seems like an error in how the `ButtonPlusHub` class is currently setup. There is only 1 instance but it is carrying logic for multiple devices. I need to look into changing this and maybe create a sub device for the main board to split each physical device on (button bars and display).

It's a bit hard to test this as I've only a single ButtonPlus to develop with.

**Comment by koenhendriks** [comment]
I've added the hub id as a prefix for the child devices' identifiers in [0.0.8](https://github.com/koenhendriks/ha-button-plus/releases/tag/0.0.8) this might potential fix this issue. Please remove the integration and entities manually before upgrading and after the upgrade please try again @wimjanse @nvdweem

**Comment by nvdweem** [comment]
I removed the entities and updated the integration, issue was not fixed.

![image](https://github.com/koenhendriks/ha-button-plus/assets/830783/46aa59bc-5a61-4e32-b492-40b6626c7ba3)

**Comment by wimjanse** [comment]
Issue not fixed

Same here, manually removed both entities, updated and reinstalled. 
After B+ nr 1, I assigned area "Studeerkamer" to Display and Bars 1, 2 and 3.
Thereafter, added B+ nr 2, I assigned area "Huiskamer" to Display and Bars 1, 2 and 3. Area's of B+ nr 1 are now also indicated as "Huiskamer", so cannot distinguish between both B+'s.

**Comment by koenhendriks** [comment]
Hey guys, Sorry for the late response I was on holiday. I will reopen this issue. 

I will soon receive a second Button+ device so then I'll be able to better debug this issue and hopefully come up with a solution soon.

**Comment by wimjanse** [comment]
Hi Koen,

some additional info:

I see the displays and the bars of the two B+'s as one device (i.e. one device for the displays, one device for Bar-1, id for Bar-2 and id for Bar-3).
Within the device, I can distinguish between the two B+'s based on entities, so for instance within the Bar-1 (device) I have entities for buttons of  Bar-1 of B+ nr.1 and for the buttons of Bar-1 of B+ nr.2 .

Hope this helps,

Rgds,
Wim
